### ISSUE TITLE
extend fields on cloud events

### ISSUE THREAD

**Issue by luisescobar89** [keptn/spec#19]
add "event type/severity" field to sh.keptn.event.problem.open and sh.keptn.event.problem cloud events

**Comment by christian-kreuzberger-dtx** [comment]
Hi and thank you for your proposal.

For Dynatrace the following "severities" are available within the problem notification:

> {ProblemSeverity}: Severity level of the problem. Possible values are AVAILABILITY, ERROR, PERFORMANCE, RESOURCE_CONTENTION, or CUSTOM_ALERT.

For Prometheus we would have to check, but I guess we could always fall back to a `CUSTOM_ALERT` in case nothing of the above works.

Maybe it also makes sense to define an action that should happen depending on the type. For instance, issues with "Availability" could just trigger a notification via slack, while errors or performance could trigger a feature-flag or scale-up remmediation action, etc...

Anyway, this sounds like a cool idea and I would like to ask you if you could write a [KEP (Keptn enhancement proposal)](https://github.com/keptn/enhancement-proposals)? This would allow the community to discuss this idea openly.
