### ISSUE TITLE
ProblemDetails Example wrong

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [keptn/spec#29]
The `ProblemDetails` field in the [cloudevents.md](https://github.com/keptn/spec/blob/master/cloudevents.md) example shows `"ProblemDetails": "Pod name",` whereas it's actually passed like this:

```
"ProblemDetails":{"displayName":"641","endTime":-1,"hasRootCause":false,"id":"1234_5678V2","impactLevel":"SERVICE","severityLevel":"PERFORMANCE","startTime":1587624420000,"status":"OPEN"}
```

**Comment by johannes-b** [comment]
Thanks for your hint. Actually, the example shown in the spec is for Prometheus where "ProblemDetails:" has the value of the "Pod name". 

For a Dynatrace problem, the value of "ProblemDetails" is the payload you mentioned. 

In #30 , the example of a Dynatrace problem is contained.

**Comment by Dynatrace-Adam-Gardner** [comment]
So the `value` could be a string or an object depending on whether prometheus or Dynatrace are used (respectively)? Or is it always an object?

**Comment by johannes-b** [comment]
It is always an object regardless of the source (Dynatrace/Prometheus). Please take a look at the updated PR #30
