### ISSUE TITLE
New Spec: artifact-delivery / deploy events - should we have configuration-change in it or something else?

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/spec#44]
My proposal:

If we want to trigger artifact delivery, we should only deploy some data, e.g.:
```
keptn trigger artifact-delivery --deployment.image=docker.io/keptnexamples/carts --deployment.tag=0.11.3
```

which should result in a cloud-event that looks like this (simplified cloud-event):

```
{
    "type": "artifact-delivery",
    "data": {
        "deployment": {
               "image": "docker.io/keptnexamples/carts",
               "tag": "0.11.3"
         }
    }
}
```

And then shipcard-controller will send a deploy.triggered with the same data.

@bacherfl could you please add the resulting cloud-events of our current implementation (master branch) as a comment?

**Comment by jetzlstorfer** [comment]
This is way more intuitive than the current implementation.
Will we get rid of "configuration-changed" events as well? As they don't reflect well what is actually happening.

**Comment by christian-kreuzberger-dtx** [comment]
There was no result on this issue yet, let's discuss it in refinement.

**Comment by DavidPHirsch** [comment]
@thisthat should we keep this open?
