### ISSUE TITLE
Keptn CloudEvents: Auto-Generate JSON Schema and JSON Examples

### ISSUE THREAD

**Issue by warber** [keptn/spec#51]
Currently, the Keptn Cloudevent Spec page is created manually.
Due to the error-prone nature of this process, it is very hard to keep the JSON examples and JSON schema descriptions in sync and up to date.

Task: 

The go structs representing the cloud events (mainly in `keptn/go-utils`) shall be used to auto-generate JSON schema files and JSON examples which can then be used in the keptn spec for our cloud events. Note that it might be necessary to add additional metadata to the existing go structs.

Initial work on generating the `cloudevents.md` file has been done [here](https://github.com/warber/keptn-dev-tools/tree/main/cloudevent-spec-gen) There are some Tasks left:

- [x] Add `jsonschema` tags to the golang structs to make the generated JSON schema more descriptive (add type information, enums, quantities, etc...)
- [x] Fix https://github.com/keptn/keptn/issues/2830 which causes the generated schema generation to output weird `$ref` fields (see json schema for `EvaluationTriggeredEventData`
- [x] Move code to one of the keptn repositories
- [ ] Nice to have: trigger the generation of the `cloudevents.md` file automatically via a GH action.

**Comment by warber** [comment]
> Nice to have: trigger the generation of the cloudevents.md file automatically via a GH action.

@christian-kreuzberger-dtx Now, that you are our mighty GH-action guru, do you feel motivated to target this task? :P

**Comment by christian-kreuzberger-dtx** [comment]
I'll help!
