### ISSUE TITLE
Keptn CloudEvents: Explain what gitCommit is and why we need it

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/spec#53]
When reading CloudEvents spec, it is not clear what `gitCommit` is and why I need it.

`gitCommit` appears in multiple cloudevents, e.g., deployment (here it actually makes sense, if we consider our helm-service), but also evaluation, as well as also `action` (e.g., `action.finished`).
![image](https://user-images.githubusercontent.com/56065213/104592965-4f7eca00-566f-11eb-9e60-e8062010da80.png)

![image](https://user-images.githubusercontent.com/56065213/104592947-48f05280-566f-11eb-81a6-31332ba27383.png)

To be clear, I know that `gitCommit` means it should be a commit hash of a git commit, but of "what" (and "why")? 
The Git config repo? What if I don't have one (e.g., unleash-service is an action-provider and does not need to have access to a Git repository at all)?

Also, what is the added benefit of having a `gitCommit` in certain cloud-events (but not all)?

**Comment by DavidPHirsch** [comment]
@thisthat keep or close?
