### ISSUE TITLE
Missing Keptn CloudEvent evaluation.invalidated in 0.2.0-alpha

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/spec#55]
In 0.1.7 we still had evaluation.invalidated: https://github.com/keptn/spec/blob/0.1.7/cloudevents.md#evaluation-invalidated

This is missing in the 0.2.0-alpha spec.

We should introduce this CloudEvent again, but using our new CloudEvents spec, e.g.:

```
sh.keptn.event.invalidate-evaluation.(triggered/started/finished)
```

with a similar payload than before.

**Comment by johannes-b** [comment]
Tasks:
* [ ] Check that `.invalidated` for evaluation is in the spec (do we need to add it to the automation tool?)

Create an issue in keptn/keptn: 
* [ ] Double-check in the Bridge, which event name is used for invalidating an evaluation (`sh.keptn.events` vs `sh.keptn.event')
* [ ] Set the correct id for the .invalidated event in the Bridge
* [ ] Update of query in MongoDB datastore + Consider to ensure 0.7.x backwards compatibility
