### ISSUE TITLE
Keptn CloudEvents: Project.Create / Service.Create / Service.Delete etc... need to be streamlined

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/spec#56]
Right now we have “internal” events that are fired when a project or a service is created or deleted, e.g., [project.create.triggered](https://github.com/keptn/spec/blob/0.2.0-alpha/cloudevents.md#project-create-triggered), [project.create.started](https://github.com/keptn/spec/blob/0.2.0-alpha/cloudevents.md#project-create-triggered) and [project.create.finished](https://github.com/keptn/spec/blob/0.2.0-alpha/cloudevents.md#project-create-triggered).

**Observation 1:** We never fire a project.create.triggered, but shipyard-controller sends a project.create.started and .finished (I guess the same is true for services).
This means that it is not possible for any other service to react on a project.create.triggered.

**Observation 2:** It seems that to counteract my first observation, some services listen on the *.create.finished events. This is suboptimal, as they sometimes event send another *.create.finished event.
For instance, helm-service sends a second service.create.finished (the other one is  from shipyard-controller)

**Suggested fix:**
Provide post-*-create cloud-events, e.g.:
post-project-create.triggered
post-service-create.triggered

**Comment by DavidPHirsch** [comment]
@thisthat same question
