### ISSUE TITLE
Keptn CloudEvents: Naming of get-sli

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/spec#57]
Question: Considering all our CloudEvent naming (e.g., test, deployment, evaluation), should `get-sli` be renamed to something that aligns with the other names, e.g., `sli-retrieval`?

**Comment by jetzlstorfer** [comment]
Agreed. I would go for `sli-retrieval` as suggested.

**Comment by johannes-b** [comment]
`sli-retrieval` sounds good. This is also how we call it in the Bridge for 0.7.x: 

![image](https://user-images.githubusercontent.com/729071/105461204-32f51a00-5c8d-11eb-840b-858f51584c3d.png)
