### ISSUE TITLE
Double-check all cloud-events before release

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn/spec#61]
Before we release Keptn 0.8.0 we need to double-check every cloud-event and every payload attribute
* whether it is needed
* whether it is used (currently)
* whether it is documented properly within the spec

**Comment by DavidPHirsch** [comment]
@thisthat keep or close?

**Comment by thisthat** [comment]
Spec are at version 0.2.4 where this issue was for milestone 0.2.0 - we can close
