### ISSUE TITLE
aggregate keptn json schemas into `schema` folder for publishing in schemastore

### ISSUE THREAD

**Issue by sudiptob2** [keptn/spec#99]
**Is your feature request related to a problem? Please describe.**
**Ketpn** JSON schemas are defined in the `.md` files. It would be nice if we create a folder and aggregate schema definition there.

**Describe the solution you'd like**
I am working on the issue [#9452](https://github.com/keptn/keptn/issues/9452) related to publishing Keptn schemas in JSON [Schemastore]( https://www.schemastore.org/json/).
It is possible to publish self-hosted schemas in the Schemastore. If we host the file in **keptn/spec** repo then it will be easy to refer to the schemas in the schema catalog of the [Schemastore]( https://www.schemastore.org/json/) without needing to create the files in the **schemastore** repo.

**Describe alternatives you've considered**
We can directly create JSON schemas in the [schemastore repository](https://github.com/SchemaStore/schemastore). However In my opinion, it would be more maintainable if we define the schemas in **keptn/spec** repo and refer them in the catalog.

**Comment by odubajDT** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
